services:
  frontend:
    image: easy-rag-frontend
    build:
      dockerfile: frontend.Dockerfile
      context: ./frontend
    ports:
      - 8501:8501
    network_mode:
      "host"
    volumes:
      - ~/code/easy-rag/data:/app/data
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes: 
      - ./ollama/ollama:/root/.ollama
    network_mode:
      "host"
    devices:
      - nvidia.com/gpu=all