networks:
  app-network:
    driver: bridge

services:
  frontend:
    image: easy-rag-frontend
    build:
      dockerfile: frontend.Dockerfile
      context: ./frontend
    ports:
      - 8501:8501
    # network_mode:
    #   "host"
    networks:
      - app-network
    volumes:
      - ~/code/easy-rag/data:/app/data
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    # network_mode:
    #   "host"
    networks:
      - app-network
    # devices: