services:
  frontend:
    image: easy-rag-frontend
    build:
      dockerfile: frontend.Dockerfile
      context: ./frontend
    ports:
      - 8501:8501
    volumes:
      - ~/code/easy-rag/data:/app/data
    depends_on:
      - db
    networks:
      - net
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes: 
      - ./ollama/ollama:/root/.ollama
    networks:
      - net
    devices:
      - nvidia.com/gpu=all
  db:
    image: chromadb/chroma:latest
    volumes:
     - db_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - 8000:8000
    networks:
      - net
  parser:
    image: easy-rag-parser
    build:
      dockerfile: parser.Dockerfile
      context: ./parser
    restart: unless-stopped
    volumes:
      - ~/code/easy-rag/data:/app/data
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  db_data:
    driver: local
     